DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS BOOK_AUTHOR;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;

CREATE TABLE AUTHORS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255)
);

CREATE TABLE BOOKS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(16) UNIQUE,
    TITLE VARCHAR(255),
    PAGES INTEGER,
    PUB_DATE DATE
);

CREATE TABLE BOOK_AUTHOR (
    BOOK_ID BIGINT,
    AUTHOR_ID BIGINT,
    PRIMARY KEY (BOOK_ID, AUTHOR_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

CREATE TABLE SALES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOK_ID BIGINT,
    PRICE DECIMAL(10, 2),
    CHANNEL VARCHAR(255),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);
